# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frankendeploy < Formula
  desc "CLI to deploy Symfony applications with FrankenPHP"
  homepage "https://github.com/yoanbernabeu/frankendeploy"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.13.0/frankendeploy_0.13.0_darwin_amd64.tar.gz"
      sha256 "6268a4f0f752a3a47f8d149e23b6c844bdf9d3caff38f364628ddbad416168e9"

      def install
        bin.install "frankendeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.13.0/frankendeploy_0.13.0_darwin_arm64.tar.gz"
      sha256 "ad742a2a5b737c67da79d88d70574783af0922ae3300936cb2f936882fa5ee6d"

      def install
        bin.install "frankendeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.13.0/frankendeploy_0.13.0_linux_amd64.tar.gz"
      sha256 "a4b1cd0dc7d9b2b191d6ae30dad8b82f9140c1ca28d6f9ecb7cc3ac773205ca0"

      def install
        bin.install "frankendeploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.13.0/frankendeploy_0.13.0_linux_arm64.tar.gz"
      sha256 "a5ec2bcd1b3b6993cd4b27a3cb7abf5b25e5a71b75cca6f5999c35627060bacb"

      def install
        bin.install "frankendeploy"
      end
    end
  end

  test do
    system "#{bin}/frankendeploy", "--version"
  end
end
