# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frankendeploy < Formula
  desc "CLI to deploy Symfony applications with FrankenPHP"
  homepage "https://github.com/yoanbernabeu/frankendeploy"
  version "0.14.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.14.1/frankendeploy_0.14.1_darwin_amd64.tar.gz"
      sha256 "cf910757f51e0783a326293c9dd1d406cf3a29926468cd9a7570b8c84737ed3a"

      define_method(:install) do
        bin.install "frankendeploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.14.1/frankendeploy_0.14.1_darwin_arm64.tar.gz"
      sha256 "eab813bd6d4c612d7c5baf7ddfae54a0a3177eee5d2f638c85101ad1aeba452e"

      define_method(:install) do
        bin.install "frankendeploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.14.1/frankendeploy_0.14.1_linux_amd64.tar.gz"
      sha256 "1963037a7f601bcd9392b667909a129334381594d8b4eb416ce8491772517abb"
      define_method(:install) do
        bin.install "frankendeploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/frankendeploy/releases/download/v0.14.1/frankendeploy_0.14.1_linux_arm64.tar.gz"
      sha256 "84c3f44a90c9ad716a54867a25fe5016c927bb57d6d848ba8ab35c856153a300"
      define_method(:install) do
        bin.install "frankendeploy"
      end
    end
  end

  test do
    system "#{bin}/frankendeploy", "--version"
  end
end
