# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grepai < Formula
  desc "Privacy-first semantic code search CLI"
  homepage "https://github.com/yoanbernabeu/grepai"
  version "0.36.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.36.1/grepai_0.36.1_darwin_amd64.tar.gz"
      sha256 "e1ec7c8136b16f6b7df3a79660586ca39db8e1f3aabf534994b0796030d17f88"

      define_method(:install) do
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.36.1/grepai_0.36.1_darwin_arm64.tar.gz"
      sha256 "5067ee7fa109f79d332b90858d4eaf8ec94fe0536e1ca0c753daf6f5a6bd05b9"

      define_method(:install) do
        bin.install "grepai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.36.1/grepai_0.36.1_linux_amd64.tar.gz"
      sha256 "320283da0ef4e5876ac900fa7c2bf2d99686ce5916a5e4b6fe6539c702329807"
      define_method(:install) do
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.36.1/grepai_0.36.1_linux_arm64.tar.gz"
      sha256 "1c756b987aea4b3a0c8165a28d2ba0371b9103bb727a75cf3b109b71084668b4"
      define_method(:install) do
        bin.install "grepai"
      end
    end
  end

  test do
    system "#{bin}/grepai", "--version"
  end
end
