# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grepai < Formula
  desc "Privacy-first semantic code search CLI"
  homepage "https://github.com/yoanbernabeu/grepai"
  version "0.27.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.27.0/grepai_0.27.0_darwin_amd64.tar.gz"
      sha256 "24db2d4e3a864162f1dc3a7c9b688077bdffc100902717c0eca848c7a7663ab0"

      def install
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.27.0/grepai_0.27.0_darwin_arm64.tar.gz"
      sha256 "b0b7a3b0f3adfba85ed18cf820758008809a5c440a36b0cabf59aa1c6f90006a"

      def install
        bin.install "grepai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.27.0/grepai_0.27.0_linux_amd64.tar.gz"
      sha256 "37dfd179f70258ae74b4d41e81943de5f090e86285e5b5b13f97d520af6eac71"
      def install
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.27.0/grepai_0.27.0_linux_arm64.tar.gz"
      sha256 "91ca6331c8da4fed2343da257b9e974524d01f1e37e8913d3d89a661cc97830b"
      def install
        bin.install "grepai"
      end
    end
  end

  test do
    system "#{bin}/grepai", "--version"
  end
end
