# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grepai < Formula
  desc "Privacy-first semantic code search CLI"
  homepage "https://github.com/yoanbernabeu/grepai"
  version "0.37.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.37.0/grepai_0.37.0_darwin_amd64.tar.gz"
      sha256 "ee2b42fdda863ca16f7cd4965f2e8c67d73e34520231bf7a594f2b4ecba7ccfd"

      define_method(:install) do
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.37.0/grepai_0.37.0_darwin_arm64.tar.gz"
      sha256 "7ca7d771f8913265329f11c699137c887d29853d8d04e1610d3d93e0abd73427"

      define_method(:install) do
        bin.install "grepai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.37.0/grepai_0.37.0_linux_amd64.tar.gz"
      sha256 "f4862fb939d45f7ce1e1d3d97269d14ac5882e7c5614aecee16df3ae486466f8"
      define_method(:install) do
        bin.install "grepai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoanbernabeu/grepai/releases/download/v0.37.0/grepai_0.37.0_linux_arm64.tar.gz"
      sha256 "d55b16073a977a2f19dbfca73e14f9322d68ae478d8d84c2655ed7b482fa5438"
      define_method(:install) do
        bin.install "grepai"
      end
    end
  end

  test do
    system "#{bin}/grepai", "--version"
  end
end
